server:
  port: 0

spring:
  application:
    name: ms-mercado
  profiles:
    active: dev
  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /doc/swagger-ui/index.html
  api-docs:
    path: /ms-mercado/api-docs

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_arcade_mercado_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/db_arcade_mercado_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/db_arcade_mercado_prod?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
